// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package models

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Participant ルーム内の参加者一覧
type Participant struct {
	// Attributes ユーザーに関連付けられたカスタム属性
	Attributes *map[string]string `json:"attributes,omitempty"`

	// Identity ユーザーID_RandomUUID
	Identity *string `json:"identity,omitempty"`

	// JoinedAt 参加した時刻
	JoinedAt *time.Time `json:"joinedAt,omitempty"`

	// Name 表示名
	Name *string `json:"name,omitempty"`
}

// RoomWithParticipants defines model for RoomWithParticipants.
type RoomWithParticipants struct {
	Participants []Participant `json:"participants"`

	// RoomId ルームのID
	RoomId openapi_types.UUID `json:"roomId"`
}

// GetLiveKitTokenParams defines parameters for GetLiveKitToken.
type GetLiveKitTokenParams struct {
	// Room 参加するルームのUUID
	Room openapi_types.UUID `form:"room" json:"room"`
}

// LiveKitWebhookApplicationWebhookPlusJSONBody defines parameters for LiveKitWebhook.
type LiveKitWebhookApplicationWebhookPlusJSONBody = map[string]interface{}

// LiveKitWebhookApplicationWebhookPlusJSONRequestBody defines body for LiveKitWebhook for application/webhook+json ContentType.
type LiveKitWebhookApplicationWebhookPlusJSONRequestBody = LiveKitWebhookApplicationWebhookPlusJSONBody
